name: Jakarta Housing Price

on:
  schedule:
    - cron: 42 09 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository content
        uses: actions/checkout@v2
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install requirements
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: data scraping
        env:
          BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        run: python 01_data_scraping.py

      - name: data cleaning
        env:
          BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        run: python data_cleaning.py

      - name: data storing
        env:
          BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        run: python data_storing.py

      - name: update README
        run: python update_README.py

      - name: commit and push README
        run: |
          git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
          git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
          git add README.md
          git commit -m "Updated README"
          git push